name: lab03
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  bullseye2d: ^1.0.12
  test: ^1.26.3

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  coverage: ^1.15.0
  lints: ^6.0.0
